---
title: "从新冠疫情的发展规律和<br>信心指数看复工复产的合<br>适时间"
author: "Wonder Women"
date: "2020/4/10"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## 01 引言

<br>**报告文章**

- 探析数据规律 抗击新型病毒 ———新型冠状病毒肺炎发展规律研究
- 新型冠状病毒感染肺炎疫情发展及信心指数
- 科学推进，步步为赢——从数据分析看复工复产 


<br><br><br>**数据来源**

- 国家卫生健康委员会网站
- 新浪网站

## 02 研究背景

<br>自2020年1月以来，新型冠状病毒疫情迅速蔓延，各地确诊病例增加。疫情受到各地政府高度关注，相继启动重大突发卫生事件I级响应并采取不同程度的隔离措施。2020年1月30日，国际卫生组织将此次疫情列为“国际公众卫生紧急事件”。在加强医疗援助及实施隔离措施的同时，全球科研人员对新冠病毒从流行病学、病理学和药理学3个领域分析，为抗击疫情提供了有力的学术支持。
<br>中国举全国之力来控制疫情，并且可喜的是，大部分地区的疫情目前已经开始趋于稳定。但与此同时，整个社会也为此付出了高昂的代价，如何理性认识疫情现状和顺利复工复产，将会成为目前乃至今后很长一段时间的难题。

## 02 研究背景


<br>因此，正确解读疫情数据，不仅有利于深刻我们对于疫情的认识，也有利于缓解担忧，从整体统计中获得信心。我们所有人都希望，整个社会最终可以用最小的代价来度过疫情时期。要想实现这一目的就需要综合各类数据进行精准统计和概率计算，来帮助我们制定科学理性的控制疫情和经济恢复政策。


## 03 研究脉络

###  **Bernstein基函数建模**

**内容**
<br>Bernstein基函数是用控制多边形的边矢量的加权组合来对数据进行预测，并对所证指数进行了预测建模和评价。Bernstein基函数不仅具有几何直观、结构简单，而且具有优良的控制特性，且其对计算机控制和改变拟合曲线非常方便，充分体现了数据挖掘的特征。
<br>

- Bernstein基函数的定义
- Bernstein基函数的性质

<br>**目的**
<br>通过对Bernstein基函数理论知识的学习，为利用Bernstein基函数对新型冠状病毒肺炎的相关指标进行拟合分析奠定基础。

## 03 研究脉络

###  **全国新冠趋势分析**

**内容**
<br>利用Bernstein基函数分别对新型冠状病毒肺炎的确诊人数、疑似人数、死亡人数以及治愈人数进行趋势拟合并对分析结果进行解读。
<br><br>**目的**
<br>探析新型冠状病毒肺炎发展规律


## 03 研究脉络

###  **信心指数及关联分析**

**内容**
<br>

- 信心指数的构建与解读
- 关联性分析

     确诊病例与疑似病例
<br> 死亡病例与确诊病例

<br>**目的**
<br>通过构建信心指数以及对Bernstein基函数趋势拟合结果的进一步分析，从数理角度反映大家对战胜疫情的信心在逐渐增强，也为有计划地实现复工复产提供数据支持。


## 03 研究脉络

###  **聚类分析及复工复产的建议**

**内容**
<br>

- 聚类分析
   <br>层次聚类分析
   <br>K-means聚类法
- 分组特征剖析
- 针对性建议

<br>**目的**
<br>根据不同省份受疫情影响程度的不同，提出不同的复工复产建议，助力实现科学有序的复工复产。
